### ISSUE TITLE
Add comments on codes for Type of Ending of the crop 

### ISSUE THREAD

**Issue by hdmarrou** [mariegosme/SSM.R#6]
add correspondance between type of end et code number

**Comment by mariegosme** [comment]
to add in the excel file (allvariables, in savedeachday sheet):
1 "normal", 2 "low LAI", 3 "not sowed", 4 "stopDAP", 5 "killed by flood", 6 "not yet"

**Comment by mariegosme** [comment]
I added the explaination in allvariables.xlsx. But anyway the output is a factor, it should print with the levels, not the numbers anyway
