### ISSUE TITLE
bug in the calculation o reduction of soil evaporation

### ISSUE THREAD

**Issue by hdmarrou** [mariegosme/SSM.R#8]
should be: 
EOS = EOS * Exp(-0.22 * STBLW / 10)               (Salado and sinclair 2013)

was:
EOS = EOS * (1.5 - 0.2 * Application.WorksheetFunction.Ln(100 * STBLW / 10))

**Comment by mariegosme** [comment]
done: cPotentialSoilEvaporation <- cPotentialSoilEvaporation * exp(-0.22 * ALLDAYDATA$sStubleWeight/10)
